app_akuntansi/urls.py
from django.urls import path
from .import views

app_name = 'app_akuntansi'

urlpatterns = [
    path('',views.Dashboard.as_view(), name='dashboard'),
    path('customer/',views.customer, name='customer'),
    path('customer/edit/<int:id_input>/', views.edit_customer, name='edit_customer'),
    path('customer/delete/<int:id_input>/',views.customer_delete, name='customer_delete'),
    path('addcustomer/',views.tambah_customer, name='tambah_customer'),
    path('suplier/',views.suplier, name='suplier'),
    path('addsuplier/',views.tambah_suplier,name='tambah_suplier'),
    path('suplier/delete/<int:id_input>/',views.suplier_delete, name='suplier_delete'),
    path('suplier/edit/<int:id_input>/', views.edit_suplier, name='edit_suplier'),
    path('kode_akun/', views.kode_akun, name='kode_akun'),
    path('addkode_akun/', views.tambah_kode_akun, name='tambah_kode_akun'), 
    path('kode_akun/delete/<int:id_input>/',views.kode_akun_delete, name='kode_akun_delete'),
    path('edit_kode_akun/<int:id_input>/',views.edit_kode_akun, name='edit_kode_akun'),
    path('item/',views.item, name='item'),
    path('addItem/',views.tambah_item,name='tambah_item'),
    path('item/delete/<int:id_input>/',views.item_hapus,name='item_hapus'),
    path('edit_item/<int:id_input>/',views.edit_item,name='edit_item'),
    path('pembelian/',views.pembelian, name='pembelian'),
    path('transaksiPembelian/',views.form_transaksi_pembelian, name='form_transaksi_pembelian'),
    path('editDataPembelian/<int:id>/',views.edit_form_pembelian, name='edit_data_pembelian'),
    path('pembelian/delete/<int:id>/', views.hapus_form_pembelian, name='hapus_pembelian'),
    path('penjualan/', views.penjualan, name='penjualan'),
]   

skripsiAkuntansi/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_akuntansi.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title></title>
  <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
  <link href="/your-path-to-fontawesome/css/all.css" rel="stylesheet">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'stl.css' %}">
</head>
<body class="bg-dark">

 <nav class="navbar navbar-expand-lg navbar-light fixed-top bg-default shadow-sm p-3 mb-5 bg-default rounded">
  <a class="navbar-brand font-weight-bold" href="{% url 'app_akuntansi:dashboard' %}">
    <img style="height: 50px;"  width="60px" src="{% static 'logohome.png' %}" alt="">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown ml-lg-4">
        <a style="color: white;" class="nav-link dropdown-toggle font-weight-bold" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Master
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href=""><b>Customer</b></a>
          <a class="dropdown-item" href="{% url 'app_akuntansi:customer' %}">Customer</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#"><b>Suplier</b></a>
          <a class="dropdown-item" href="{% url 'app_akuntansi:suplier' %}">Suplier</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#"><b>Akun</b></a>
          <a class="dropdown-item" href="{% url 'app_akuntansi:kode_akun' %}">Kode Akun</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#"><b>Barang</b></a>
          <a class="dropdown-item" href="{% url 'app_akuntansi:item' %}">Item Barang</a>
        </div>
      </li>
      <li class="nav-item dropdown ml-3">
        <a style="color:white;" class="nav-link dropdown-toggle font-weight-bold" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Transaksi
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#"><b>Uang Keluar</b></a>
          <a class="dropdown-item" href="{% url 'app_akuntansi:pembelian' %}">Pembelian</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#"><b>Uang Masuk</b></a>
          <a class="dropdown-item" href="#">Penjualan</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#"><b>Jurnal</b></a>
          <a class="dropdown-item" href="#">Jurnal Umum</a>
        </div>
      </li>
      <li class="nav-item dropdown ml-3">
        <a style="color: white;" class="nav-link dropdown-toggle font-weight-bold" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Laporan
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#"><b>Penjualan</b></a>
          <a class="dropdown-item" href="#">Berdasarkan Invoice</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#"><b>Pembelian</b></a>
          <a class="dropdown-item" href="#">Berdasarkan Tagihan</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#"><b>Stok</b></a>
          <a class="dropdown-item" href="#">Available Stock</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#"><b>Keuangan</b></a>
          <a class="dropdown-item" href="#">Jurnal</a>
          <a class="dropdown-item" href="#">Buku Besar</a>
          <a class="dropdown-item" href="#">Neraca Saldo</a>
          <a class="dropdown-item" href="#">Laba Rugi</a>
          <a class="dropdown-item" href="#">Neraca</a>
        </div>
      </li>
    </ul>
    <i class="fas fa-user"></i>
</nav>
</div><br><br><br>
<!-- content -->
<div class="container-fluid mt-4">
    <div style="height:45px; background-color: rgb(225, 235, 231)" class="p-2 mb-4 rounded">
        <a class="nav-link p-1 font-weight-bold pt-0" href="{% url 'app_akuntansi:dashboard' %}" title="">Dashboard / {{head}}</a><br>
    </div>
    {% block content_body %}
        
    {% endblock  %}
</div>
 

<script src="{% static 'jquery.js' %}"></script>
<script src="{% static 'popper.js' %}"></script>
<script src="{% static 'bootstrap.js' %}"></script>

</body>
</html>

templates/customer.html
{% extends 'base.html' %}
{% load static %}

{% block content_body %}
	<div class="card">
		<div class="card-header" style="height: 50px;">
			<h4>{{head}}</h4>
		</div>
		<div class="card-body">
		<div class="row">
				<div class="col-sm-6">
					<button
						type="button"
						class="btn btn-success shadow">
						<a href="{% url 'app_akuntansi:tambah_customer' %}"><i class="fas fa-pen mr-1"></i>Tambah Data <strong>+</strong></a>
					</button>

					<div class="dropdown">
						<button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							10
						</button>
						<div class="dropdown-menu" aria-labelledby="dropdownMenu2">
							<button class="dropdown-item" type="button">1</button>
						</div>
					</div>
				</div>
				<div class="col-sm-6">
					<div style="margin-left: 530px;" class="dropdown tools">
					<button class="btn btn-secondary dropdown-toggle shadow " type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						TOOLS
					</button>
					<div class="dropdown-menu" aria-labelledby="dropdownMenu2">
						<button class="dropdown-item" type="button">CETAK PDF</button>
						<button class="dropdown-item" type="button">CETAK Excel</button>
					</div>
					</div>
				</div>
			</div>
			<table class="table table-bordered">
				<thead>
					<tr>
						<th scope="col">No</th>
						<th scope="col">Nama</th>
						<th scope="col">Email</th>
						<th scope="col">Alamat</th>
						<th scope="col">Telp</th>
						<th scope="col">Aksi</th>
					</tr>
				</thead>
				<tbody>
				{% for customer in customer %}
					<tr>
						<th scope="row">1</th>
						<td>{{customer.nama}}</td>
						<td>{{customer.email}}</td>
						<td>{{customer.alamat}}</td>
						<td>{{customer.telp}}</td>
						<td>
							<a class="btn btn-success" href="{% url 'app_akuntansi:edit_customer' id_input=customer.id %}">
								<i class="far fa-edit"></i>
								Edit
							</a>
							<a class="btn btn-danger" href="{% url 'app_akuntansi:customer_delete' id_input=customer.id %}">
								<i class="far fa-trash-alt"></i>
								Delete</a>
						</td>
					</tr>
				{% endfor %}
				</tbody>
			</table>
		</div>
	</div>

{% endblock  %}
	

templates/edit_customer.html
{% extends 'base.html' %}
{% load static %}


{% block content_body %}
<div class="card">
    <div class="card-header" style="height: 50px;">
		<h4>{{head}}</h4>
    </div>
    <div class="card-body">
        <form method="POST">
            {% csrf_token %}
            <div class="form-group row">
                <label for="nama" class="col-sm-2 col-form-label">Nama</label>
                <div class="col-sm-4">
                    <input name="nama" required="true" value="{{cust_edit.nama}}" class="form-control" type="text" id="nama">
                </div>
                <div class="col-sm-4"></div>
            </div>
            <div class="form-group row">
                <label for="email" class="col-sm-2 col-form-label">Email</label>
                <div class="col-sm-4">
                    <input name="email" class="form-control" value="{{cust_edit.email}}" type="email" id="email">
                </div>
                <div class="col-sm-4"></div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label" for="alamat">Alamat</label>
                <div class="col-sm-4">
                    <input required="true" name="alamat" value="{{cust_edit.alamat}}" class="form-control" type="text" id="alamat">
                </div>
                <div class="col-sm-4"></div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label" for="telp">Telp</label>
                <div class="col-sm-4">
                    <input class="form-control" name="telepon" value="{{cust_edit.telp}}" type="text" id="telp">
                </div>
            </div>
            <a style="margin-left: 171px;text-decoration: none;"  href="{% url 'app_akuntansi:customer' %}">Batal</a>
            <input class="btn btn-primary ml-2" value="Simpan" type="submit">
        </form>
    </div>
</div>
{% endblock  %}

templates/edit_item.html
{% extends 'base.html' %}
{% load static %}

{% block content_body %}
<div class="card">
    <div class="card-header" style="height: 50px;">
		<h4>{{head}}</h4>
    </div>
    <div class="card-body">
        <form method="POST">
            {% csrf_token %}
            <div class="form-group row">
                <label for="kode_item" class="col-sm-2 col-form-label">Kode Item</label>
                <div class="col-sm-3">
                    <input name="kode_item" value="{{item_edit.kode_item}}" required="true" class="form-control" type="text" id="kode_item">
                </div>
                <div class="col-sm-3"></div>
            </div>
            <div class="form-group row">
                <label for="nama_item" class="col-sm-2 col-form-label">Nama Item</label>
                <div class="col-sm-3">
                    <input name="nama_item" value="{{item_edit.nama_item}}" class="form-control" type="text" id="nama_item">
                </div>
                <div class="col-sm-3"></div>
            </div>
            <div class="form-group row">
                <label for="uom" class="col-sm-2 col-form-label">Uom</label>
                <div class="col-sm-3">
                    <input name="uom" value="{{item_edit.uom}}" class="form-control" type="text" id="uom">
                </div>
                <div class="col-sm-3"></div>
            </div>
            <div class="form-group row">
                <label for="harga_beli" class="col-sm-2 col-form-label">Harga Beli</label>
                <div class="col-sm-3">
                    <input name="harga_beli" value="{{item_edit.harga_beli}}" class="form-control" type="text" id="harga_beli">
                </div>
                <div class="col-sm-3"></div>
            </div>
            <div class="form-group row">
                <label for="harga_jual" class="col-sm-2 col-form-label">Harga Jual</label>
                <div class="col-sm-3">
                    <input name="harga_jual" value="{{item_edit.harga_jual}}" class="form-control" type="text" id="harga_jual">
                </div>
                <div class="col-sm-3"></div>
            </div>

            <a style="margin-left: 171px; text-decoration: none;" href="{% url 'app_akuntansi:item' %}">Batal</a>
            <button class="btn btn-primary ml-2" type="submit">Simpan</button>
        </form>
    </div>
</div>
{% endblock  %}
    

templates/edit_kode_akun.html
{% extends 'base.html' %}
{% load static %}

{% block content_body %}
<div class="card">
    <div class="card-header" style="height: 50px;">
		<h4>{{head}}</h4>
    </div>
    <div class="card-body">
        <form method="POST">
            {% csrf_token %}
            <div class="form-group row">
                <label for="kode_akun" class="col-sm-2 col-form-label">Kode akun</label>
                <div class="col-sm-5">
                    <input name="kode_akun" value="{{akun_edit.kode_akun}}" required="true" class="form-control" type="text" id="kode_akun">
                </div>
                <div class="col-sm-5"></div>
            </div>
            <div class="form-group row">
                <label for="nama" class="col-sm-2 col-form-label">Nama</label>
                <div class="col-sm-5">
                    <input name="nama" value="{{akun_edit.nama}}" class="form-control" type="text" id="nama">
                </div>
                <div class="col-sm-5"></div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label" for="telp">Saldo Normal</label>
                <div class="col-sm-5">
                    <select class="form-control" name="saldo_normal">
                      <option value="Debit">Debit</option>
                      <option value="Kredit">Kredit</option>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label" for="a_p">Akun Pembayaran</label>
                <div class="col-sm-5">
                    <select class="form-control" name="akun_pembayaran" id="a_p">
                      <option value="Y">Y</option>
                      <option value="N">N</option>
                    </select>
                </div>
            </div>
            <a style="margin-left: 172px;text-decoration: none;" href="{% url 'app_akuntansi:kode_akun' %}">Batal</a>
            <button class="btn btn-primary ml-2" type="submit">Simpan</button>
        </form>
    </div>
</div>
{% endblock  %}
    

templates/form_transaksi_pembelian.html
{% extends 'base.html' %}
{% load static %}

{% block content_body %}
<div class="card">
    <div class="card-header" style="height: 50px;">
    <h4>{{head}}</h4>
    </div>
    <div class="card-body">
        <form method="POST">
            {% csrf_token %}
            <div class="form-group row">
                <label for="nota_number" class="col-sm-2 col-form-label">Nota Number</label>
                <div class="col-sm-3">
                    <input name="nota_number" required="true" class="form-control" type="text" id="nota_number">
                </div>
                <div class="col-sm-5"></div>
            </div>
            <div class="form-group row">
                <label for="tanggal" class="col-sm-2 col-form-label">Tanggal Masuk</label>
                <div class="col-sm-3">
                    <input name="tanggal" class="form-control" type="date" id="tanggal">
                </div>
                <div class="col-sm-5"></div>
            </div>
            <div class="form-group row">
              <label class="col-sm-2 col-form-label" for="pemasok">Pemasok</label>
              <div class="col-sm-3">
                  <select class="form-control" name="pemasok">
                    
                    {% for spl in supliers %}
                    <option value="{{spl.id}}">{{spl.nama}}</option>
                    {% endfor %}
                      
                  </select>
              </div>
            </div>
            <!-- start modal -->
            <div id="myModal" class="modal fade" role="dialog">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">  
                    <h4 class="modal-title"><b>Form Input Item Data</b></h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                  </div>
                  <div class="modal-body p-5 ml-5 mr-5">     
                      <div class="form-group row">
                          <div class="col-sm-4">
                            <label class="form-label">ID item</label>
                          </div>
                          <div class="col-sm-5">
                            <select class="form-control" name="id_item" id="id_barang">
                              {% for item in items  %}
                              <option value="{{item.id}}">{{item.kode_item}}</option>
                              {% endfor %}
                            </select>
                          </div>
                      </div>
                      <div class="form-group row">
                          <div class="col-sm-4">
                            <label class="form-label">Item Nama</label>
                          </div>
                          <div class="col-sm-8">
                              <input name="item_nama" required="true" class="form-control" type="text" id="item_nama">
                          </div>
                      </div>
                      <div class="form-group row">
                          <div class="col-sm-4">
                            <label class="form-label">Uom</label>
                          </div>
                          <div class="col-sm-6">
                              <input name="uom" required="true" class="form-control" type="text" id="uom">
                          </div>
                      </div>
                      <div class="form-group row">
                          <div class="col-sm-4">
                            <label class="form-label">Harga</label>
                          </div>
                          <div class="col-sm-6">
                              <input name="harga" required="true" class="form-control" type="text" id="harga">
                          </div>
                      </div>
                      <div class="form-group row">
                          <div class="col-sm-4">
                            <label class="form-label">Quantity</label>
                          </div>
                          <div class="col-sm-6">
                              <input name="quantity" required="true" class="form-control" type="text" id="quantity">
                          </div>
                      </div>
                    </div>
                    <div class="modal-footer">
                      <a class="btn btn-danger" href="{% url 'app_akuntansi:form_transaksi_pembelian' %}">Cancel</a>
                      <input class="btn btn-success" type="submit" value="Input">
                    </div> 
                  </div>
                </div>
              </div>

        </form>

            <!-- batas -->
          <div class="btn btn-success" data-toggle="modal" data-target="#myModal">
            <i class="fas fa-pen"></i>   
            Tambah Data <b>+</b>
          </div>
        <table class="table table-bordered mt-4">
          <thead>
            <tr>
              <th scope="col">Nama</th>
              <th scope="col">Unit</th>
              <th scope="col">Quantity</th>
              <th scope="col">Harga</th>
              <th scope="col">Total</th>
              <th scope="col">Aksi</th>
            </tr>
          </thead>
          <tbody>
            {% for p in pembelians %}
              <tr>
                <th>{{p.nama}}</th>
                <td>{{p.uom}}</td>
                <td>{{p.quantity}}</td>
                <td>{{p.harga}}</td>
                <td>{{p.total}}</td>
                <td><a href="{% url 'app_akuntansi:edit_data_pembelian' p.id %}">Edit</a>
                    <a href="{% url 'app_akuntansi:hapus_pembelian' p.id %}">Delete</a></td>
                    
              </tr>
            {% endfor %}
            <tr>
              <th>Grand Total</th>
              <td></td>
              <td></td>
              <td></td>
              <td><b>{{total}}</b></td>
              <td></td>
            </tr>
          </tbody>
        </table>
    </div>
    <!-- modal -->
    
      <!-- ending modal -->
  <div class="container mb-5">
    <a class="btn btn-success" href="{% url 'app_akuntansi:pembelian' %}">Save</a>
    <a class="btn btn-dark" href="">Cancel</a>
  </div>

{% endblock  %}
    

templates/item.html
{% extends 'base.html' %}
{% load static %}

{% block content_body %}
<div class="card">
  <div class="card-header" style="height: 50px;">
    <h4>{{head}}</h4>
  </div>
  <div class="card-body mt-0">
  <div class="row">
      <div class="col-sm-6">
        <button type="button"class="btn btn-success shadow">
          <a href="{% url 'app_akuntansi:tambah_item' %}">
            <i class="fas fa-pen"></i>
            Tambah Data <strong>+</strong></b>
          </a>
        </button>

        <div class="dropdown">
          <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            10
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
            <button class="dropdown-item" type="button">1</button>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div style="margin-left: 530px;" class="dropdown tools">
        <button class="btn btn-secondary dropdown-toggle shadow" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          TOOLS
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
          <button class="dropdown-item" type="button">CETAK PDF</button>
          <button class="dropdown-item" type="button">CETAK Excel</button>
        </div>
        </div>
      </div>
    </div>
    <table class="table table-bordered mt-4">
      <thead>
        <tr>
          <th scope="col">Kode Item</th>
          <th scope="col">Nama</th>
          <th scope="col">Uom</th>
          <th scope="col">Harga Beli</th>
          <th scope="col">Harga Jual</th>
          <th scope="col">Aksi</th>
        </tr>
      </thead>
      <tbody>
        
        {% for item in item  %}
          <tr>
            <td>{{item.kode_item}}</td>
            <td>{{item.nama_item}}</td>
            <td>{{item.uom}}</td>
            <td>{{item.harga_beli}}</td>
            <td>{{item.harga_jual}}</td>
            <td><a class="btn btn-success" href="{% url 'app_akuntansi:edit_item' id_input=item.id %}">
                <i class="far fa-edit"></i>
                Edit</a>
              <a class="btn btn-danger" href="{% url 'app_akuntansi:item_hapus' id_input=item.id %}">
                <i class="far fa-trash-alt"></i>
                Delete</a></td></td>
          </tr>
        {% endfor %}
        
      </tbody>
    </table>
  </div>
</div>

{% endblock  %}

  

templates/kode_akun.html
{% extends 'base.html' %}
{% load static %}


{% block content_body %}
<div class="card">
  <div class="card-header" style="height: 50px;">
    <h4>{{head}}</h4>
  </div>
  <div class="card-body">
  <div class="row ">
      <div class="col-sm-6">
        <button
         type="button"
          class="btn btn-success shadow">
          <a href="{% url 'app_akuntansi:tambah_kode_akun' %}">
            <i class="fas fa-pen"></i>
            Tambah Data <strong>+</strong></a>
        </button>

        <div class="dropdown">
          <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            10
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
            <button class="dropdown-item" type="button">1</button>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div style="margin-left: 530px;" class="dropdown tools">
        <button class="btn btn-secondary dropdown-toggle shadow" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          TOOLS
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
          <button class="dropdown-item" type="button">CETAK PDF</button>
          <button class="dropdown-item" type="button">CETAK Excel</button>
        </div>
        </div>
      </div>
    </div>
    <table class="table table-light mt-4">
      <thead>
        <tr>
          <th scope="col">Kode Akun</th>
          <th scope="col">Nama Akun</th>
          <th scope="col">Saldo Normal</th>
          <th scope="col">Akun Pembayaran</th>
          <th scope="col">Aksi</th>
        </tr>
      </thead>
      <tbody>
        
        {% for kode_akun in kode_akun  %}
          <tr>
            <td>{{kode_akun.kode_akun}}</td>
            <td>{{kode_akun.nama}}</td>
            <td>{{kode_akun.saldo_normal}}</td>
            <td>{{kode_akun.akun_pembayaran}}</td>
            <td><a class="btn btn-success" href="{% url 'app_akuntansi:edit_kode_akun' id_input=kode_akun.id %}">
                <i class="far fa-edit"></i>
                Edit</a>
              <a class="btn btn-danger" href="{% url 'app_akuntansi:kode_akun_delete' id_input=kode_akun.id %}">
                <i class="far fa-trash-alt"></i>
                Delete</a></td></td>
          </tr>
        {% endfor %}
        
      </tbody>
    </table>
  </div>
</div>

{% endblock  %}

  

templates/suplier.html
{% extends 'base.html' %}
{% load static %}

{% block content_body %}
	<div class="card">
		<div class="card-header" style="height: 50px;">
			<h4>{{head}}</h4>
		</div>
		<div class="card-body">
		<div class="row">
				<div class="col-sm-6">
					<button type="button"class="btn btn-success shadow">
						<a href="{% url 'app_akuntansi:tambah_suplier' %}">
							<i class="fas fa-pen"></i>
							Tambah Data <strong>+</strong></b></a>
					</button>

					<div class="dropdown">
						<button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							10
						</button>
						<div class="dropdown-menu" aria-labelledby="dropdownMenu2">
							<button class="dropdown-item" type="button">1</button>
						</div>
					</div>
				</div>
				<div class="col-sm-6">
					<div style="margin-left: 530px;" class="dropdown tools">
					<button class="btn btn-secondary dropdown-toggle shadow" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						TOOLS
					</button>
					<div class="dropdown-menu" aria-labelledby="dropdownMenu2">
						<button class="dropdown-item" type="button">CETAK PDF</button>
						<button class="dropdown-item" type="button">CETAK Excel</button>
					</div>
					</div>
				</div>
			</div>
			<table class="table table-bordered mt-4">
				<thead>
					<tr>
						<th scope="col">No</th>
						<th scope="col">Nama</th>
						<th scope="col">Email</th>
						<th scope="col">Alamat</th>
						<th scope="col">Telp</th>
						<th scope="col">Aksi</th>
					</tr>
				</thead>
				<tbody>
				{% for suplier in suplier %}
					<tr>
						<th scope="row">1</th>
						<td>{{suplier.nama}}</td>
						<td>{{suplier.email}}</td>
						<td>{{suplier.alamat}}</td>
						<td>{{suplier.telp}}</td>
						<td><a class="btn btn-success" href="{% url 'app_akuntansi:edit_suplier' id_input=suplier.id %}">
								<i class="far fa-edit"></i>
									Edit</a>
								<a class="btn btn-danger" href="{% url 'app_akuntansi:suplier_delete' id_input=suplier.id %}">
									<i class="far fa-trash-alt"></i>
									Delete</a></td>
					</tr>
				{% endfor %}
				</tbody>
			</table>
		</div>
	</div>

{% endblock  %}
	